import { AppProvider } from "@/context/Appcontext";
import "@/styles/globals.css";
import { AnimatePresence } from "framer-motion";
import Head from "next/head";

export default function App({ Component, pageProps, router }) {
  return (
    <>

      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/S.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/S.png"
        />
        {/* <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        /> */}
        {/* <link rel="manifest" href="/site.webmanifest" /> */}
      </Head>
      <AppProvider>
        <AnimatePresence mode="wait">
            <Component key={router.route} location={router.route} {...pageProps} />
        </AnimatePresence>
      </AppProvider>
    </>
  );
}
